### ISSUE TITLE
Epic: Bot/Watcher Capabilities - Event-Driven AI Assistant

### ISSUE THREAD

**Issue by rshade** [rshade/cronai#118]
# Epic: Bot/Watcher Capabilities - Event-Driven AI Assistant

## Overview
Transform CronAI from a scheduled/cron-based pull model to support an event-driven push model that can act as an intelligent bot, responding to GitHub events in real-time.

## Current State
CronAI currently operates on a **scheduled/cron-based pull model** where:
- Tasks run at predetermined times
- Prompts are executed against AI models periodically
- Responses are processed through various channels (GitHub, Slack, email, etc.)

## Proposed Bot/Watcher Feature
Transform CronAI to also support an **event-driven push model** that can:
1. **Watch GitHub repositories** for events (issues, PRs, commits, mentions)
2. **Act as a GitHub App/Bot** that responds when assigned or mentioned
3. **Process webhooks** to trigger AI tasks based on external events
4. **Maintain state** between interactions for context-aware responses

### 1. New Components Needed

```
// internal/watcher/
├── interface.go          // Watcher interface
├── github_watcher.go     // GitHub webhook handler
├── event_router.go       // Routes events to appropriate handlers
└── state_manager.go      // Maintains conversation context

// internal/bot/
├── github_bot.go         // GitHub bot logic
├── conversation.go       // Conversation state management
└── handlers/             // Event-specific handlers
    ├── issue_handler.go
    ├── pr_handler.go
    └── mention_handler.go
```

### 2. Event-Driven Architecture

```
GitHub Events → Webhook Endpoint → Event Router → Bot Handler → AI Model → Response Processor
                                         ↓
                                   State Manager
```

### 3. Key Features

1. **Webhook Server**: HTTP endpoint to receive GitHub webhooks
2. **Event Filtering**: Process only relevant events (assignments, mentions, specific labels)
3. **Context Management**: Maintain conversation history per issue/PR
4. **Smart Responses**: Use AI to generate contextual responses based on:
   - Issue/PR content
   - Previous comments
   - Repository context
   - User permissions

### Phase 1: Foundation (2-3 weeks)
- [ ] Create webhook server component
- [ ] Implement basic event router
- [ ] Add GitHub App authentication support
- [ ] Create bot configuration schema
- [ ] Add --mode flag for operation modes (cron, bot, queue)

### Phase 2: Core Bot Features (3-4 weeks)
- [ ] Implement issue assignment handler
- [ ] Add mention detection (@cronai-bot)
- [ ] Create conversation state manager
- [ ] Build context-aware prompt generation

### Phase 3: Advanced Features (2-3 weeks)
- [ ] Add PR review capabilities
- [ ] Implement label-based triggers
- [ ] Create bot command system (/cronai help, /cronai analyze)
- [ ] Add rate limiting and queue management

### Phase 4: Integration (1-2 weeks)
- [ ] Integrate with existing processor system
- [ ] Add bot-specific templates
- [ ] Create deployment guides for GitHub App
- [ ] Add monitoring and metrics

## Configuration Example

```yaml
# cronai.bot.config
bot:
  github:
    app_id: 12345
    private_key_path: /path/to/key.pem
    webhook_secret: "your-webhook-secret"
    
watchers:
  - type: github
    repos:
      - owner/repo1
      - owner/repo2
    events:
      - issues.opened
      - issues.assigned
      - pull_request.opened
      - issue_comment.created
    triggers:
      - type: mention
        pattern: "@cronai-bot"
      - type: label
        labels: ["ai-review", "needs-analysis"]
      - type: assignment
        
    actions:
      - model: claude
        prompt: product_manager_bot
        processor: github-comment:{{.repo}}#{{.issue_number}}
```

## Benefits

1. **Proactive Assistance**: Bot responds immediately to events
2. **Context Awareness**: Maintains conversation history
3. **Reduced Manual Work**: Automates routine PM tasks
4. **Integration**: Works alongside existing cron-based tasks
5. **Scalability**: Can handle multiple repos and high event volumes

## Technical Considerations

1. **Security**: Webhook validation, GitHub App permissions
2. **Rate Limits**: Respect GitHub API limits
3. **Idempotency**: Handle duplicate webhook deliveries
4. **Error Recovery**: Graceful handling of failures
5. **Testing**: Mock webhook events for testing

## Operation Modes

CronAI will support multiple operation modes via a `--mode` flag:
- **cron** (default): Traditional scheduled task execution
- **bot**: Event-driven webhook handler for real-time responses
- **queue**: Job queue processor for distributed execution (future)

## Success Criteria

- [ ] Bot can respond to GitHub events within seconds
- [ ] Maintains conversation context across interactions
- [ ] Handles at least 100 events per minute
- [ ] 99.9% webhook delivery success rate
- [ ] Zero duplicate responses
- [ ] Full integration with existing processor system

## Related Issues
- Queue/Grid Computing Epic: #[TBD]
- Existing GitHub processor: #113

## Acceptance Criteria
- [ ] All Phase 1-4 features implemented
- [ ] Comprehensive documentation
- [ ] Unit and integration tests with >80% coverage
- [ ] Performance benchmarks documented
- [ ] Security review completed
- [ ] Deployment guide for GitHub App created
