### ISSUE TITLE
Implement chain-based workflow system using LangChainGo patterns

### ISSUE THREAD

**Issue by rshade** [rshade/cronai#169]
## Problem Statement

CronAI currently supports only single-prompt execution. For sophisticated agentic workflows, we need the ability to compose multiple steps, manage state between operations, and create conditional logic flows.

## Proposed Solution

Implement a chain-based workflow system inspired by LangChainGo's chain patterns to enable complex multi-step AI operations.

### 1. Chain Interface
```go
type Chain interface {
    Call(ctx context.Context, inputs map[string]interface{}) (map[string]interface{}, error)
    Apply(ctx context.Context, inputsList []map[string]interface{}) ([]map[string]interface{}, error)
    GetInputKeys() []string
    GetOutputKeys() []string
}
```

#### Sequential Chain
- Execute steps in sequence
- Pass outputs from one step as inputs to the next
- Support conditional branching based on results

#### Parallel Chain
- Execute multiple operations concurrently
- Aggregate results before proceeding
- Useful for gathering multiple data sources

#### Loop Chain
- Support iterative operations
- Conditional termination based on criteria
- Useful for refinement workflows

### 3. Chain Configuration
Support chain definitions in configuration files:
```yaml
chains:
  - name: "analysis_workflow"
    type: "sequential"
    steps:
      - model: "claude"
        prompt: "analyze_data"
        output_key: "analysis"
      - model: "openai" 
        prompt: "summarize_analysis"
        input_key: "analysis"
        output_key: "summary"
      - processor: "slack"
        input_key: "summary"
```

### 4. Integration with Existing Systems
- Extend cron configuration to support chain execution
- Maintain backward compatibility with single-prompt tasks
- Support chains in bot and queue modes

## Benefits

- **Complex Workflows**: Enable sophisticated multi-step operations
- **Conditional Logic**: Support branching and decision-making
- **State Management**: Maintain context between steps
- **Reusability**: Define workflows once, use multiple times
- **Agentic Behavior**: Foundation for autonomous AI agents

## Use Cases

1. **Multi-step Analysis**: Gather data → Analyze → Summarize → Report
2. **Content Generation**: Research → Draft → Review → Publish
3. **Decision Making**: Assess situation → Generate options → Evaluate → Decide
4. **Quality Assurance**: Generate content → Review → Fix issues → Validate

## Tasks

- [ ] Design chain interface and core abstractions
- [ ] Implement sequential chain execution
- [ ] Implement parallel chain execution  
- [ ] Add chain configuration parsing (YAML/JSON)
- [ ] Integrate chains with cron scheduler
- [ ] Add chain support to bot mode
- [ ] Add chain support to queue mode
- [ ] Implement state management between chain steps
- [ ] Add conditional branching support
- [ ] Create chain validation and testing tools
- [ ] Add comprehensive test coverage
- [ ] Update documentation with chain examples

## Acceptance Criteria

- [ ] Sequential chains execute steps in correct order
- [ ] Parallel chains execute steps concurrently
- [ ] State is properly managed between chain steps
- [ ] Chains can be defined in configuration files
- [ ] Existing single-prompt functionality still works
- [ ] Error handling works correctly in chain context
- [ ] Performance is acceptable for complex workflows
- [ ] Comprehensive test coverage exists
- [ ] Documentation includes clear examples

## Configuration Example

```yaml
# cronai.config.yaml
schedules:
  - cron: "0 9 * * *"
    chain: "daily_report"
    processor: "email-team@company.com"

chains:
  daily_report:
    type: "sequential"
    steps:
      - name: "gather_metrics"
        model: "claude"
        prompt: "system_metrics"
        output_key: "metrics"
      - name: "analyze_trends"
        model: "openai"
        prompt: "trend_analysis"
        input_key: "metrics"
        output_key: "analysis"
      - name: "generate_report"
        model: "claude"
        prompt: "daily_report_template"
        input_keys: ["metrics", "analysis"]
        output_key: "report"
```

## Related Issues

- Part of Epic: LangChainGo Integration (#167)
- Builds on model abstraction refactoring (#168)
- Relates to Enhanced Templating System (Epic #1)

## Dependencies

- Model abstraction refactoring (#168) should be completed first
- YAML/JSON configuration parsing capabilities
