### ISSUE TITLE
Enhanced prompt templating system using LangChainGo patterns

### ISSUE THREAD

**Issue by rshade** [rshade/cronai#171]
## Problem Statement

CronAI's current prompt system uses simple file-based prompts with basic variable substitution. For sophisticated agentic workflows, we need more advanced templating capabilities including conditional logic, few-shot learning, dynamic examples, and chat-specific formatting.

## Proposed Solution

Implement an enhanced prompt templating system inspired by LangChainGo's prompt management patterns.

### 1. Prompt Template Interface
```go
type PromptTemplate interface {
    Format(ctx context.Context, values map[string]interface{}) (string, error)
    FormatMessages(ctx context.Context, values map[string]interface{}) ([]Message, error)
    GetInputVariables() []string
    Validate() error
}
```

#### Basic String Template
- Enhanced version of current system
- Support for complex variable substitution
- Conditional blocks and loops
- Template inheritance

#### Chat Prompt Template
- Structured message templates for conversational AI
- Support for system, user, and assistant message roles
- Dynamic message construction based on context

#### Few-Shot Prompt Template
- Support for example-based prompting
- Dynamic example selection based on context
- Configurable number of examples

#### Pipeline Template
- Compose multiple templates in sequence
- Output of one template becomes input to next
- Useful for complex prompt construction

#### Conditional Logic
```yaml
# Example template with conditionals
template:  < /dev/null | 
  {{#if user_type == "admin"}}
  You have administrative privileges. 
  {{else}}
  You have standard user privileges.
  {{/if}}
  
  Please {{action}} the following:
  {{content}}
```

#### Loops and Iteration
```yaml
# Example template with loops
template: |
  Process the following items:
  {{#each items}}
  - Item {{@index}}: {{this.name}} ({{this.type}})
  {{/each}}
```

#### Template Inheritance
```yaml
# base_template.yaml
template: |
  {{> header}}
  {{content}}
  {{> footer}}

# specific_template.yaml
extends: "base_template"
content: |
  Specific content here
```

#### Static Examples
- Pre-defined examples in template files
- Support for different example sets per use case

#### Dynamic Example Selection
- AI-powered example selection based on context
- Similarity-based example matching
- Configurable selection strategies

#### Chain Integration
- Templates work seamlessly with chain workflows
- Template outputs can be inputs to subsequent chain steps
- Support for template composition in chains

#### Memory Integration
- Templates can access conversation memory
- Dynamic context injection from memory stores
- Memory-aware example selection

## Benefits

- **Flexibility**: Support for complex prompt construction logic
- **Reusability**: Template inheritance and composition
- **Context Awareness**: Dynamic content based on situation
- **Few-Shot Learning**: Powerful example-based prompting
- **Chat Support**: Proper conversational AI formatting
- **Maintainability**: Separation of logic and content

## Use Cases

1. **Adaptive Prompts**: Different behavior based on user type or context
2. **Few-Shot Learning**: Dynamic examples for better AI performance
3. **Multi-turn Conversations**: Proper chat message formatting
4. **Complex Reports**: Template-driven report generation
5. **Conditional Workflows**: Different prompts based on conditions

## Tasks

- [ ] Design enhanced prompt template interfaces
- [ ] Implement basic string template with conditionals/loops
- [ ] Implement chat prompt template for conversations
- [ ] Implement few-shot prompt template with examples
- [ ] Add template inheritance and composition
- [ ] Implement dynamic example selection
- [ ] Add template validation and testing tools
- [ ] Integrate templates with chain system
- [ ] Add memory integration for context-aware templates
- [ ] Migrate existing prompts to new system
- [ ] Add comprehensive test coverage
- [ ] Update documentation with template examples

## Acceptance Criteria

- [ ] Templates support conditional logic and loops
- [ ] Chat templates properly format conversational messages
- [ ] Few-shot templates dynamically select relevant examples
- [ ] Template inheritance works correctly
- [ ] Templates integrate with chain workflows
- [ ] Memory context is available in templates
- [ ] Existing prompt files continue to work
- [ ] Performance is acceptable for complex templates
- [ ] Comprehensive test coverage exists
- [ ] Documentation includes clear examples

### Conditional Template
```yaml
# cron_prompts/adaptive_analysis.yaml
name: "adaptive_analysis"
type: "conditional"
template: |
  {{#if data_type == "financial"}}
  Analyze the following financial data with emphasis on:
  - Revenue trends
  - Cost analysis
  - Profitability metrics
  {{else if data_type == "technical"}}
  Analyze the following technical data with emphasis on:
  - Performance metrics
  - Error rates
  - System health
  {{else}}
  Provide a general analysis of the following data:
  {{/if}}
  
  Data: {{data}}
  
  {{#if include_recommendations}}
  Please include specific recommendations for improvement.
  {{/if}}
```

### Few-Shot Template
```yaml
# cron_prompts/code_review.yaml
name: "code_review"
type: "few_shot"
examples:
  - input: "function add(a, b) { return a + b }"
    output: "Simple function, consider adding type annotations and input validation."
  - input: "def process_data(data): return [x*2 for x in data if x > 0]"
    output: "Good use of list comprehension. Consider adding docstring and type hints."
template: |
  Review the following code and provide constructive feedback:
  
  {{#each examples}}
  Example:
  Code: {{this.input}}
  Review: {{this.output}}
  
  {{/each}}
  
  Now review this code:
  Code: {{code}}
  Review:
```

### Chat Template
```yaml
# cron_prompts/support_bot.yaml
name: "support_bot"
type: "chat"
system_message: |
  You are a helpful customer support assistant. Use previous conversation 
  context to provide personalized assistance.
  
  Customer info: {{customer_info}}
messages:
  - role: "system"
    content: "{{system_message}}"
  {{#if memory}}
  {{#each memory.messages}}
  - role: "{{this.role}}"
    content: "{{this.content}}"
  {{/each}}
  {{/if}}
  - role: "user"
    content: "{{user_message}}"
```

## Related Issues

- Part of Epic: LangChainGo Integration (#167)
- Relates to Enhanced Templating System (Epic #1)
- Works with chain-based workflows (#169)
- Integrates with memory system (#170)

## Dependencies

- YAML/JSON parsing for template definitions
- Template engine (consider handlebars-like syntax)
- Integration points with chains and memory systems
