### ISSUE TITLE
Implement tool integration framework using LangChainGo patterns

### ISSUE THREAD

**Issue by rshade** [rshade/cronai#172]
## Problem Statement

CronAI currently has limited extensibility - it can only execute AI prompts and process responses through predefined processors. For sophisticated agentic workflows, AI agents need access to external tools and capabilities to interact with the world.

## Proposed Solution

Implement a tool integration framework inspired by LangChainGo's tools pattern to enable AI agents to use external capabilities and APIs.

### 1. Tool Interface
```go
type Tool interface {
    Name() string
    Description() string
    Execute(ctx context.Context, input string) (string, error)
    GetInputSchema() map[string]interface{} // JSON Schema for input validation
}
```

#### Web Tools
- HTTP API client for external services
- Support for GET, POST, PUT, DELETE operations
- Authentication handling (API keys, OAuth, etc.)
- Rate limiting and retry logic

#### File System Tools
- Read/write files
- Directory operations
- File search and manipulation
- Safe path handling with sandboxing

#### Database Tools
- SQL query execution
- NoSQL database operations
- Connection pooling and management
- Query validation and safety

#### System Tools
- Command execution (with security controls)
- System information gathering
- Process management
- Environment variable access

#### Custom Tools
- Plugin architecture for user-defined tools
- Language-agnostic tool definitions
- Configuration-driven tool loading

### 3. Tool Registry
```go
type ToolRegistry interface {
    Register(tool Tool) error
    Get(name string) (Tool, error)
    List() []Tool
    LoadFromConfig(config ToolConfig) error
}
```

### 4. Agent Integration
- Tools available to AI models through structured prompts
- Function calling support for compatible models (OpenAI, Claude)
- Automatic tool result formatting
- Tool chaining and composition

## Benefits

- **Extended Capabilities**: AI agents can interact with external systems
- **Modularity**: Tools can be added/removed without core changes
- **Security**: Controlled access to system resources
- **Flexibility**: Support for various tool types and protocols
- **Agentic Behavior**: Foundation for autonomous AI agents

## Use Cases

1. **Data Integration**: Query databases, call APIs, read files
2. **System Administration**: Monitor systems, execute commands
3. **Content Management**: Create, update, and organize content
4. **Communication**: Send messages, create notifications
5. **Automation**: Trigger workflows, manage processes

## Tasks

- [ ] Design tool interface and abstractions
- [ ] Implement tool registry system
- [ ] Create HTTP API tool for web services
- [ ] Create file system tool with security controls
- [ ] Create database tool for SQL operations
- [ ] Add tool configuration system
- [ ] Integrate tools with model providers (function calling)
- [ ] Add tool validation and testing framework
- [ ] Implement tool chaining and composition
- [ ] Add comprehensive security controls
- [ ] Create tool documentation and examples
- [ ] Add comprehensive test coverage

## Acceptance Criteria

- [ ] Tools can be registered and discovered dynamically
- [ ] HTTP tools can call external APIs safely
- [ ] File system tools respect security boundaries
- [ ] Database tools handle connections properly
- [ ] AI models can invoke tools through function calling
- [ ] Tool results integrate with chain workflows
- [ ] Security controls prevent unauthorized access
- [ ] Error handling works correctly for tool failures
- [ ] Comprehensive test coverage exists
- [ ] Documentation includes clear examples

## Configuration Example

```yaml
# cronai.config.yaml
tools:
  - name: "github_api"
    type: "http"
    base_url: "https://api.github.com"
    auth:
      type: "bearer"
      token: "${GITHUB_TOKEN}"
    endpoints:
      - name: "create_issue"
        method: "POST"
        path: "/repos/{owner}/{repo}/issues"
        
  - name: "file_manager"
    type: "filesystem"
    root_path: "/safe/working/directory"
    permissions: ["read", "write"]
    
  - name: "database"
    type: "sql"
    driver: "postgres"
    connection: "${DATABASE_URL}"
    allowed_operations: ["SELECT", "INSERT", "UPDATE"]

chains:
  research_and_report:
    steps:
      - model: "claude"
        prompt: "research_query"
        tools: ["github_api", "file_manager"]
      - model: "openai"
        prompt: "compile_report"
        tools: ["file_manager"]
```

### Sandboxing
- Restrict file system access to designated directories
- Limit network access to approved domains/IPs
- Resource usage limits (CPU, memory, time)

### Authentication
- Secure credential management
- Token rotation and expiration
- Audit logging of tool usage

### Validation
- Input validation using JSON schemas
- Output sanitization
- Command injection prevention

### GitHub API Tool
```yaml
name: "github_api"
description: "Interact with GitHub repositories"
type: "http"
endpoints:
  create_issue:
    method: "POST"
    path: "/repos/{owner}/{repo}/issues"
    input_schema:
      type: "object"
      properties:
        owner: {"type": "string"}
        repo: {"type": "string"}
        title: {"type": "string"}
        body: {"type": "string"}
      required: ["owner", "repo", "title"]
```

### File System Tool
```yaml
name: "file_ops"
description: "File system operations"
type: "filesystem"
operations:
  read_file:
    description: "Read content from a file"
    input_schema:
      type: "object"
      properties:
        path: {"type": "string"}
      required: ["path"]
  write_file:
    description: "Write content to a file"
    input_schema:
      type: "object"
      properties:
        path: {"type": "string"}
        content: {"type": "string"}
      required: ["path", "content"]
```

## Related Issues

- Part of Epic: LangChainGo Integration (#167)
- Works with chain-based workflows (#169)
- Enhances agentic capabilities across all modes

## Dependencies

- Model abstraction supporting function calling
- Security framework for tool sandboxing
- Configuration system for tool definitions
